# mkdocs.yml
site_name: 奶茶勞工生活
site_url: https://chocochocococo.github.io/milktea-workerlife-wiki/  # 換成您的網址
site_author: 奶茶勞工生活說明書

# 外觀設定
# mkdocs.yml

# --- 外觀設定 ---
# 請將您原本的 theme 區塊完整換成下面這段
theme:
  name: material
  language: zh-TW
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  
  # ✨ 啟用顏色選擇器 (淺色/深色模式切換) ✨
  palette:
    # 淺色模式 (牛奶可可)
    - media: "(prefers-color-scheme: light)"
      scheme: default # "default" 是淺色模式的代號
      primary: brown # 主題色調，可選 brown, teal, orange 等
      accent: deep-orange # 強調色，可選 amber, indigo 等
      toggle:
        icon: material/weather-sunny
        name: 切換至深色模式
        
    # 深色模式 (黑巧克力)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # "slate" 是深色模式的代號
      primary: brown
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: 切換至淺色模式

# 導覽列設定
nav:
  - 首頁: index.md
  - 開始勞工生活: introduce.md
  - 指令說明: 
    - 指令一覽: command/commandlist.md
    - 一般指令: command/commandfornormal.md
    - 工作指令: command/commandforwork.md
    - 交易指令: command/commandfortrade.md
    - 飲品指令: command/commandfordrink.md
    - 伴侶指令: command/commandforpartner.md
    - 寵物指令: command/commandforpet.md
    - 冒險指令: command/commandforadv.md
  - 各項目一覽:
    - 飲品一覽: list/drinklist.md
    - 商品一覽: list/shoplist.md
    - 原料一覽: list/itemlist.md
    - 冒險地點一覽: list/advlocationlist.md
    - 冒險怪物一覽: list/advmonsterlist.md
    - 冒險頭目一覽: list/advbosslist.md

# Markdown 擴充功能
markdown_extensions:
  - admonition # 提示框
  - pymdownx.details # 可折疊區塊
  - pymdownx.superfences # 程式碼塊加強
  
  # ✨ 新增的目錄功能 ✨
  - toc:
      permalink: true # 為每個標題增加一個可點擊的錨點連結
      toc_depth: 3 # 目錄顯示到H3標題，您可以依需求調整

extra_css:
    - stylesheets/extra.css